"""Display names for source headers, kept beside the original wording.

This is a rendering table, not a judgement: nothing here changes what is
selected, compared or validated. A term with no entry is shown unchanged, so
the analysis degrades to the original wording instead of guessing.
"""

TERMS = {
    # 재무 지표
    "revenue": "매출",
    "total revenue": "총매출",
    "net revenue": "순매출",
    "sales": "매출",
    "net income": "순이익",
    "net loss": "순손실",
    "gross profit": "매출총이익",
    "operating income": "영업이익",
    "operating profit": "영업이익",
    "ebit": "영업이익",
    "ebitda": "상각전영업이익",
    "eps": "주당순이익",
    "diluted eps": "희석 주당순이익",
    "basic eps": "기본 주당순이익",
    "total assets": "총자산",
    "total debt": "총부채",
    "net debt": "순부채",
    "total equity": "총자본",
    "cash": "현금",
    "cash and equivalents": "현금 및 현금성자산",
    "free cash flow": "잉여현금흐름",
    "capex": "설비투자",
    "market cap": "시가총액",
    "market capitalization": "시가총액",
    "tev": "기업가치",
    "enterprise value": "기업가치",
    "dividend yield": "배당수익률",
    "book value": "장부가치",
    "day close price": "종가",
    "volume": "거래량",
    # 인원
    "headcount": "인원",
    "employees": "직원 수",
    "total employees": "전체 직원 수",
    "department": "부서",
    "role": "직무",
    "roles": "직무",
    "analyst": "애널리스트",
    "finance": "재무",
    "legal": "법무",
    "engineering": "엔지니어링",
    "marketing": "마케팅",
    "sales & marketing": "영업·마케팅",
    "general & administrative": "일반관리",
    "research & development": "연구개발",
    # 사건·공시 유형
    "key developments": "주요 사건",
    "key development": "주요 사건",
    "key development date": "사건 발생일",
    "key development type & category": "사건 유형",
    "key development headline": "사건 제목",
    "key development description": "사건 내용",
    "conference": "컨퍼런스",
    "company conference presentation": "기업 컨퍼런스 발표",
    "strategic alliance": "전략적 제휴",
    "client announcement": "고객 관련 발표",
    "product-related announcement": "제품 관련 발표",
    "business expansion": "사업 확장",
    "ex-dividend date, regular": "정기 배당락일",
    "ex-dividend date": "배당락일",
    "executive/board changes": "경영진·이사회 변동",
    "m&a transaction announcements": "인수합병 발표",
    "earnings calls": "실적 발표",
    "seeking to sell/divest": "매각 추진",
    # 문서·표 제목
    "financial snapshot": "재무 요약",
    "financial snapshot tearsheet": "재무 요약표",
    "company summary": "기업 요약",
    "valuation": "가치평가",
    "valuation multiples": "가치평가 배수",
    "capital structure": "자본 구조",
    "market data": "시장 지표",
    "leverage multiples": "레버리지 배수",
    "transaction comparables": "거래 비교",
    "price/volume graph": "주가·거래량 그래프",
}
